//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow_Hockey_Oyunu {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GlowHockey : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlowHockey defaultInstance = ((GlowHockey)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlowHockey())));
        
        public static GlowHockey Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int skor {
            get {
                return ((int)(this["skor"]));
            }
            set {
                this["skor"] = value;
            }
        }
    }
}
